"""A thin, scope-safe wrapper around a git repository whose work tree is the
live game directory.

Every mutating operation is confined to an explicit pathspec allowlist. The
work tree contains a lot of files wowsync must never touch -- the game client
itself, Cache/, Logs/, and the machine-local WTF files -- so `git clean` is
never used, and anything that rewrites the work tree is gated behind
`assert_index_scoped()`.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path

from .util import Fail, is_macos, log, run

COMMIT_IDENTITY = {
    "GIT_AUTHOR_NAME": "wowsync",
    "GIT_AUTHOR_EMAIL": "wowsync@localhost",
    "GIT_COMMITTER_NAME": "wowsync",
    "GIT_COMMITTER_EMAIL": "wowsync@localhost",
}


def glob_pathspec(pattern: str) -> str:
    """Translate a config glob into a git pathspec.

    `:(glob)` gives wildmatch semantics, where `*` stops at a directory
    separator and `**` crosses one -- which is what the config patterns mean.
    Without it git would treat `WTF/Account/*/SavedVariables` as matching at
    any depth.
    """
    return f":(glob){pattern}"


@dataclass
class CommitInfo:
    sha: str
    subject: str
    when: int
    machine: str


class GitRepo:
    def __init__(self, git_dir: Path, work_tree: Path):
        self.git_dir = git_dir
        self.work_tree = work_tree

    # -- plumbing -------------------------------------------------------

    def git(self, *args: str, check: bool = True, stdin: bytes | None = None):
        cmd = ["git", f"--git-dir={self.git_dir}", f"--work-tree={self.work_tree}", *args]
        return run(cmd, cwd=self.work_tree, env=COMMIT_IDENTITY, check=check, stdin=stdin)

    def out(self, *args: str, check: bool = True) -> str:
        return self.git(*args, check=check).stdout.decode("utf-8", "replace").strip()

    @property
    def exists(self) -> bool:
        return (self.git_dir / "HEAD").exists()

    # -- setup ----------------------------------------------------------

    def init(self, excludes: list[str]) -> None:
        if not self.exists:
            self.git_dir.parent.mkdir(parents=True, exist_ok=True)
            run(["git", "init", "--quiet", "--bare", str(self.git_dir)])
            # A bare repo with a work tree attached: the repo lives outside the
            # game directory so nothing in the game tree is ever surprised by a
            # stray .git, but it still tracks files in place.
            self.git("config", "core.bare", "false")
            self.git("symbolic-ref", "HEAD", "refs/heads/main")
        self.configure()
        self.write_excludes(excludes)
        self.write_attributes()

    def configure(self) -> None:
        settings = {
            # The exec bit differs between APFS and ext4 and means nothing here.
            "core.fileMode": "false",
            # SavedVariables must land on disk byte-for-byte as WoW wrote them.
            "core.autocrlf": "false",
            "core.safecrlf": "false",
            "core.logAllRefUpdates": "true",
            # Snapshots are frequent, so repack sooner than git's default of
            # 6700 loose objects. `git commit` triggers auto-gc itself, which
            # is why nothing here calls gc explicitly.
            "gc.auto": "256",
            "user.name": "wowsync",
            "user.email": "wowsync@localhost",
        }
        if is_macos():
            # APFS hands back decomposed (NFD) filenames; store the composed form
            # so addon folders with accented names match what Linux records.
            settings["core.precomposeunicode"] = "true"
        settings["core.ignoreCase"] = "true" if self._fs_is_case_insensitive() else "false"
        for key, value in settings.items():
            self.git("config", key, value)

    def _fs_is_case_insensitive(self) -> bool:
        probe = self.git_dir / ".wowsync-case-probe"
        try:
            probe.parent.mkdir(parents=True, exist_ok=True)
            probe.write_text("")
            return (self.git_dir / ".WOWSYNC-CASE-PROBE").exists()
        except OSError:
            return is_macos()
        finally:
            try:
                probe.unlink()
            except OSError:
                pass

    def write_excludes(self, patterns: list[str]) -> None:
        info = self.git_dir / "info"
        info.mkdir(parents=True, exist_ok=True)
        body = "# generated by wowsync; edits are overwritten\n" + "\n".join(patterns) + "\n"
        (info / "exclude").write_text(body)

    def write_attributes(self) -> None:
        info = self.git_dir / "info"
        info.mkdir(parents=True, exist_ok=True)
        # `-text` disables every content filter: no eol conversion, no working
        # tree munging. `-merge` makes sure git never tries to splice two
        # versions of a Lua settings file together line by line.
        (info / "attributes").write_text(
            "# generated by wowsync; edits are overwritten\n"
            "* -text -merge\n"
            "*.lua diff=lua\n"
        )

    # -- inspection -----------------------------------------------------

    def head(self) -> str | None:
        proc = self.git("rev-parse", "--verify", "--quiet", "HEAD", check=False)
        sha = proc.stdout.decode().strip()
        return sha or None

    def ref(self, name: str) -> str | None:
        proc = self.git("rev-parse", "--verify", "--quiet", name, check=False)
        sha = proc.stdout.decode().strip()
        return sha or None

    def has_common_ancestor(self, a: str, b: str) -> bool:
        """False when the two histories were started independently."""
        return self.git("merge-base", a, b, check=False).returncode == 0

    def is_ancestor(self, maybe_ancestor: str, descendant: str) -> bool:
        return self.git(
            "merge-base", "--is-ancestor", maybe_ancestor, descendant, check=False
        ).returncode == 0

    def index_differs_from_head(self) -> bool:
        if self.head() is None:
            return self.git("diff", "--cached", "--quiet", check=False).returncode != 0
        return self.git("diff", "--cached", "--quiet", "HEAD", check=False).returncode != 0

    def tracked_files(self) -> list[str]:
        out = self.out("ls-files", "-z")
        return [p for p in out.split("\0") if p]

    def assert_index_scoped(self, allowed_prefixes: list[str]) -> None:
        """Refuse to rewrite the work tree if the index reaches outside the
        directories wowsync owns. This is the last line of defence against a
        misconfigured pathspec turning `reset --hard` into data loss."""
        stray = [
            path
            for path in self.tracked_files()
            if not any(path == p or path.startswith(p.rstrip("/") + "/") for p in allowed_prefixes)
        ]
        if stray:
            raise Fail(
                "refusing to touch the work tree: the index tracks paths outside "
                f"{allowed_prefixes}: {stray[:5]}"
            )

    def merge_base(self, a: str, b: str) -> str | None:
        out = self.out("merge-base", a, b, check=False)
        return out or None

    def merge_tree(
        self, base: str, ours: str, theirs: str, strategy_option: str | None = None
    ) -> tuple[str | None, list[str]]:
        """Merge two commits in the object database, touching no files.

        Returns (tree_oid, conflicted_paths). The work tree is the live game
        directory, so merging there would mean writing conflict markers into
        files WoW is expected to parse; doing it as pure plumbing lets us
        inspect the outcome and decide before anything reaches disk.
        """
        args = ["merge-tree", "--write-tree", "--name-only"]
        if strategy_option:
            args += ["-X", strategy_option]
        args += [f"--merge-base={base}", ours, theirs]
        proc = self.git(*args, check=False)
        if proc.returncode > 1:
            log.debug("merge-tree failed: %s", proc.stderr.decode("utf-8", "replace").strip())
            return None, []
        lines = proc.stdout.decode("utf-8", "replace").splitlines()
        if not lines:
            return None, []
        tree = lines[0].strip()
        conflicts = []
        for line in lines[1:]:
            if not line.strip():
                break
            conflicts.append(line.strip())
        return tree, conflicts

    def tree_of(self, commit: str) -> str:
        return self.out("rev-parse", f"{commit}^{{tree}}")

    def changed_between(self, a: str, b: str) -> list[str]:
        out = self.out("diff", "--name-only", "-z", a, b, check=False)
        return [p for p in out.split("\0") if p]

    def commit_tree(self, tree: str, parents: list[str], message: str) -> str:
        args = ["commit-tree", tree]
        for parent in parents:
            args += ["-p", parent]
        return self.git(*args, stdin=message.encode("utf-8")).stdout.decode().strip()

    def log(self, limit: int = 20, since: str | None = None) -> list[CommitInfo]:
        args = ["log", f"-n{limit}", "--format=%H%x1f%s%x1f%ct%x1f%(trailers:key=Machine,valueonly,separator=%x2c)"]
        if since:
            args.append(f"--since={since}")
        out = self.out(*args, check=False)
        commits = []
        for line in out.splitlines():
            if not line.strip():
                continue
            parts = line.split("\x1f")
            if len(parts) < 4:
                continue
            commits.append(
                CommitInfo(sha=parts[0], subject=parts[1], when=int(parts[2]), machine=parts[3])
            )
        return commits

    # -- mutation -------------------------------------------------------

    def pattern_matches_worktree(self, pattern: str) -> bool:
        """True if the glob currently matches at least one file on disk."""
        if pattern.endswith("/**"):
            base = pattern[: -len("/**")]
            return any(
                d.is_dir() and any(child.is_file() for child in d.rglob("*"))
                for d in self.work_tree.glob(base)
            )
        return any(p.is_file() for p in self.work_tree.glob(pattern))

    def pattern_matches_index(self, pattern: str) -> bool:
        """True if the glob matches something already tracked.

        A pattern whose files were all deleted still has to be passed to
        `git add -A` so the deletion gets recorded.
        """
        return bool(self.out("ls-files", "--", glob_pathspec(pattern), check=False))

    def live_patterns(self, include: list[str]) -> list[str]:
        return [
            pattern
            for pattern in include
            if self.pattern_matches_worktree(pattern) or self.pattern_matches_index(pattern)
        ]

    def stage(self, include: list[str], forbidden: list[str]) -> None:
        """Bring the index in line with the work tree, for the allowlist only.

        `git add` treats a pathspec matching nothing as fatal, and several
        default patterns legitimately match nothing until the game has been
        played (no characters yet, so no per-character WTF folders), so dead
        patterns are dropped first. Ignored files are filtered out by
        info/exclude rather than by negative pathspecs, because naming an
        ignored path literally in a pathspec is itself a fatal error.
        """
        live = self.live_patterns(include)
        if not live:
            log.debug("no include pattern matches anything yet; nothing to stage")
            return
        self.git("add", "-A", "--", *[glob_pathspec(p) for p in live])
        self.untrack(forbidden)

    def stage_all(self) -> None:
        """Stage the entire work tree. Only for trees wowsync owns outright."""
        self.git("add", "-A", ".")

    def untrack(self, patterns: list[str]) -> None:
        """Drop files that must never be shared, if they ever got tracked.

        info/exclude stops them being added in the first place; this repairs a
        repo seeded before a pattern was added, and makes the peer drop its
        copy too instead of silently keeping a stale one.
        """
        if not patterns:
            return
        out = self.out("ls-files", "-z", "--", *[glob_pathspec(p) for p in patterns], check=False)
        paths = [p for p in out.split("\0") if p]
        if not paths:
            return
        log.warning(
            "untracking %d file(s) that should not be shared: %s",
            len(paths), ", ".join(paths[:3]),
        )
        self.git("rm", "--cached", "--quiet", "--ignore-unmatch", "--", *paths)

    def stage_blob(self, path: str, content: bytes) -> None:
        """Put `content` into the index at `path` without writing it to disk.

        Used for SavedVariables files whose machine-local globals have been
        stripped: the work tree keeps the whole file so WoW can read it, while
        the repo stores only the shared half.
        """
        sha = run(
            ["git", f"--git-dir={self.git_dir}", "hash-object", "-w", "--stdin"],
            stdin=content,
        ).stdout.decode().strip()
        self.git("update-index", "--add", "--cacheinfo", f"100644,{sha},{path}")

    def commit(self, subject: str, machine: str) -> str | None:
        if not self.index_differs_from_head():
            return None
        message = f"{subject}\n\nMachine: {machine}\n"
        self.git("commit", "--quiet", "--no-verify", "-m", message)
        return self.head()

    def read_tree(self, target: str, allowed_prefixes: list[str]) -> None:
        """Make the index and work tree match `target`, without moving HEAD.

        Only tracked files are written or removed, so untracked neighbours in
        the game directory -- Config.wtf, Cache/, the client itself -- are left
        exactly as they are.
        """
        self.assert_index_scoped(allowed_prefixes)
        self.git("read-tree", "-u", "--reset", target)

    def set_head(self, target: str) -> None:
        self.git("update-ref", "HEAD", target)

    def branch_at(self, name: str, target: str) -> None:
        self.git("update-ref", f"refs/heads/{name}", target)

    def staged_change_count(self) -> int:
        base = "HEAD" if self.head() else None
        args = ["diff", "--cached", "--numstat"]
        if base:
            args.append(base)
        out = self.out(*args, check=False)
        return len([line for line in out.splitlines() if line.strip()])

    # -- remote ---------------------------------------------------------

    def set_remote(self, url: str) -> None:
        if not url:
            return
        current = self.out("remote", "get-url", "origin", check=False)
        if current == url:
            return
        if current:
            self.git("remote", "set-url", "origin", url)
        else:
            self.git("remote", "add", "origin", url)

    def fetch(self) -> bool:
        """Update every remote-tracking ref. False only if the server is down.

        All heads are fetched in one connection rather than naming a branch,
        because naming one that does not exist yet -- an empty server, before
        either machine has pushed -- fails the same way an unreachable host
        does, and those two need very different responses.
        """
        env = dict(os.environ)
        env.setdefault("GIT_SSH_COMMAND", "ssh -o ConnectTimeout=20 -o BatchMode=yes")
        env.setdefault("GIT_TERMINAL_PROMPT", "0")
        cmd = [
            "git", f"--git-dir={self.git_dir}", f"--work-tree={self.work_tree}",
            "fetch", "--quiet", "--prune", "origin", "+refs/heads/*:refs/remotes/origin/*",
        ]
        proc = run(cmd, cwd=self.work_tree, env={**COMMIT_IDENTITY, **env}, check=False)
        if proc.returncode != 0:
            log.debug("fetch failed: %s", proc.stderr.decode("utf-8", "replace").strip())
            return False
        return True

    def push(self, branch: str, force: bool = False) -> tuple[bool, str]:
        env = dict(os.environ)
        env.setdefault("GIT_SSH_COMMAND", "ssh -o ConnectTimeout=20 -o BatchMode=yes")
        refspec = f"refs/heads/{branch}:refs/heads/{branch}"
        cmd = [
            "git", f"--git-dir={self.git_dir}", f"--work-tree={self.work_tree}",
            "push", "--quiet", "origin",
        ]
        if force:
            cmd.append("--force-with-lease")
        cmd.append(refspec)
        proc = run(cmd, cwd=self.work_tree, env={**COMMIT_IDENTITY, **env}, check=False)
        message = proc.stderr.decode("utf-8", "replace").strip()
        return proc.returncode == 0, message

    def push_branch(self, local_ref: str, remote_branch: str) -> tuple[bool, str]:
        env = dict(os.environ)
        env.setdefault("GIT_SSH_COMMAND", "ssh -o ConnectTimeout=20 -o BatchMode=yes")
        cmd = [
            "git", f"--git-dir={self.git_dir}", f"--work-tree={self.work_tree}",
            "push", "--quiet", "origin", f"{local_ref}:refs/heads/{remote_branch}",
        ]
        proc = run(cmd, cwd=self.work_tree, env={**COMMIT_IDENTITY, **env}, check=False)
        return proc.returncode == 0, proc.stderr.decode("utf-8", "replace").strip()
