"""Split a WoW SavedVariables Lua file into top-level global assignments.

WoW rewrites every SavedVariables file wholesale on logout, so the file is the
unit of change as far as git is concerned. That is a problem when one addon
stores both settings you want shared between machines and settings that are
genuinely per-machine (an output device, a UI scale pinned to one monitor).

The files are machine-generated by WoW's own serializer and have a narrow shape:
a sequence of top-level statements, each beginning at column 0 with the name of
a saved global. That lets us slice the file at global boundaries without a full
Lua parser -- we only need to know when we are at brace depth 0 and outside a
string or comment.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

# A top-level statement starts at column 0 with an identifier followed by
# an assignment (`Foo = ...`) or an index into it (`Foo["bar"] = ...`).
_TOP_LEVEL = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*)\s*(?:=[^=]|\[|\.)")


@dataclass(frozen=True)
class Chunk:
    """One top-level statement (or the file's leading comment block)."""

    name: str | None  # None for the preamble
    text: str


class _Scanner:
    """Tracks brace depth while ignoring braces inside strings and comments."""

    def __init__(self) -> None:
        self.depth = 0
        self._long_bracket_level: int | None = None  # inside [[ ]] / --[==[ ]==]

    @property
    def at_top_level(self) -> bool:
        return self.depth == 0 and self._long_bracket_level is None

    def feed(self, line: str) -> None:
        i = 0
        n = len(line)
        while i < n:
            if self._long_bracket_level is not None:
                close = "]" + "=" * self._long_bracket_level + "]"
                idx = line.find(close, i)
                if idx == -1:
                    return
                self._long_bracket_level = None
                i = idx + len(close)
                continue

            ch = line[i]

            if ch in ('"', "'"):
                i = self._skip_quoted(line, i)
                continue

            if ch == "[":
                level = _long_bracket_open(line, i)
                if level is not None:
                    self._long_bracket_level = level
                    i += level + 2
                    continue

            if ch == "-" and line.startswith("--", i):
                level = _long_bracket_open(line, i + 2)
                if level is not None:
                    self._long_bracket_level = level
                    i += level + 4
                    continue
                return  # line comment: nothing else on this line counts

            if ch in "{(":
                self.depth += 1
            elif ch in "})":
                self.depth = max(0, self.depth - 1)
            i += 1

    @staticmethod
    def _skip_quoted(line: str, i: int) -> int:
        quote = line[i]
        i += 1
        while i < len(line):
            if line[i] == "\\":
                i += 2
                continue
            if line[i] == quote:
                return i + 1
            i += 1
        return i  # unterminated on this line; WoW never emits these


def _long_bracket_open(line: str, i: int) -> int | None:
    """If a Lua long bracket `[==[` opens at `i`, return its `=` count."""
    if i >= len(line) or line[i] != "[":
        return None
    j = i + 1
    while j < len(line) and line[j] == "=":
        j += 1
    if j < len(line) and line[j] == "[":
        return j - (i + 1)
    return None


def parse_chunks(text: str) -> list[Chunk]:
    """Break a SavedVariables file into its top-level statements, in order."""
    lines = text.splitlines(keepends=True)
    scanner = _Scanner()
    chunks: list[Chunk] = []
    current_name: str | None = None
    current: list[str] = []

    for line in lines:
        starts_statement = scanner.at_top_level and bool(_TOP_LEVEL.match(line))
        if starts_statement:
            if current:
                chunks.append(Chunk(current_name, "".join(current)))
            match = _TOP_LEVEL.match(line)
            assert match is not None
            current_name = match.group(1)
            current = [line]
        else:
            current.append(line)
        scanner.feed(line)

    if current:
        chunks.append(Chunk(current_name, "".join(current)))
    return chunks


def global_names(text: str) -> list[str]:
    """Every saved global defined in the file, in file order, deduplicated."""
    seen: list[str] = []
    for chunk in parse_chunks(text):
        if chunk.name and chunk.name not in seen:
            seen.append(chunk.name)
    return seen


def split_globals(text: str, names: list[str]) -> tuple[str, str]:
    """Partition into (shared, machine_local) by top-level global name.

    Statements for a name in `names` go to the machine-local side; everything
    else, including the leading comment block, stays shared.
    """
    wanted = set(names)
    shared: list[str] = []
    local: list[str] = []
    for chunk in parse_chunks(text):
        (local if chunk.name in wanted else shared).append(chunk.text)
    return "".join(shared), "".join(local)


def join_globals(shared: str, local: str) -> str:
    """Reassemble a full SavedVariables file from its two halves.

    Top-level assignments are independent, so appending the machine-local half
    reproduces a file WoW loads identically to the one it wrote.
    """
    if not local.strip():
        return shared
    if shared and not shared.endswith("\n"):
        shared += "\n"
    return shared + local
